# Site settings
name: Team201701
email: zy18728@nottingham.edu.cn
author: Ziyao Wang
url: 
resume_site: 
github: https://github.com/Jiuxifo/
baseurl: ""
description: Attendence Management System
meta_description: Minutes;Documentation;Progress
motto: GRP Group 1 Project
banner: Attendence Management System

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Jiuxifo

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

