# Resources settings
source:      .
layouts:     ./_layouts
timezone:    Asia/Hongkong

# Site settings
email: zy18728@nottingham.edu.cn
author: Ziyao Wang
owner_name: Ziyao
github_username: Jiuxifo
repo: Jiuxifo.github.io

#Server
url: Jiuxifo.github.io
github: https://github.com/joytou/
coding: https://coding.net/joytou/
baseurl: ""

#Page settings
future: true
show_drafts: nil
lsi: true
published: false
safe: false
permalink: /:year/:month/:day/:title/
markdown: kramdown
excerpt_separator: '<!-- more -->'

exclude: ['README.md','Manifest.md']
include: ['robots.txt']

# Description
description: "Team201701 GRP website"
# Keywords
keywords:
        - "Minutes"
        - "Documents"
        - "Description"
        - "Yuanliang"
        - "Mawentai"
        - "Zhichao"
        - "Xiaodong"
        - "Jiaying"
        - "Ziyao"
        
#Update configuration
versioncode: 1
        #The current versioncode.
versionname: "1.0.1"
        #The current versionname.
remind: false
        #Whether to remind you to upgrade the latest version when there is the latest version.

#Others
#Baidu
BaiduSiteVerification: ""
#51La
51la: ""
51lamb: ""

coding_comments:
  owner: 'wusisu'
  repo: 'wusisu'
  oauth:
    client_id: '624713aab28c44e0555b0e8d5d18dece'
    client_secret: '5d2d45460648bfbd3b9f77bead1a0ac6aa7c3c95'
